In [1]:
#numpy
import numpy as np
l1 = [10,20,30,40]

In [3]:
n1 =np.array(l1)

In [4]:
n1

array([10, 20, 30, 40])

In [5]:
type(n1)

numpy.ndarray

In [7]:
#2 dimensional array
n2 = np.array([[1,2,3,4],[4,3,2,1]])

In [8]:
n2

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [9]:
type(n2)

numpy.ndarray

In [10]:
#initialize numpy array with zero
n3 = np.zeros((1,2))

In [11]:
n3

array([[0., 0.]])

In [12]:
type(n3)

numpy.ndarray

In [13]:
n4 = np.zeros((5,5))

In [14]:
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
type(n4)

numpy.ndarray

In [16]:
#initialize numpy array with same number
n5 = np.full((3,4),50)

In [17]:
n5

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50]])

In [19]:
n6 = np.arange(10,30)

In [20]:
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [25]:
n7 = np.arange(10,51,5)

In [26]:
n7

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [35]:
#initialize numpy array with random number
n8 = np.random.randint(100,200,10)

In [36]:
n8

array([130, 154, 147, 124, 144, 158, 101, 106, 183, 195])

In [38]:
#numpy shape
n9 = np.array([[1,2,3],[4,5,6]])

In [39]:
n9

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
n9.shape

(2, 3)

In [41]:
n9.shape = (3,2)

In [42]:
n9

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
# numpy vstack()
p1 =np.array([1,2,3])

In [47]:
p2 = np.array([4,5,6])

In [48]:
np.vstack((p1,p2))

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
#numpy hstack()
p3 = np.array([10,20,30])

In [50]:
p4 = np.array([40,50,60])

In [51]:
np.hstack((p3,p4))

array([10, 20, 30, 40, 50, 60])

In [52]:
# numpy coloumn_stack
p4 = np.array([6,7,8,9])

In [53]:
p5 = np.array([9,8,7,6])

In [54]:
np.column_stack((p4,p5))

array([[6, 9],
       [7, 8],
       [8, 7],
       [9, 6]])

In [55]:
#numpy intersection & difference
p6 = np.array([10,20,30,40,50,60])

In [56]:
p7 = np.array([50,60,70,80,90])

In [57]:
np.intersect1d(p6,p7)

array([50, 60])

In [58]:
np.setdiff1d(p6,p7)

array([10, 20, 30, 40])

In [59]:
np.setdiff1d(p7,p6)

array([70, 80, 90])

In [60]:
#numpy mathematics
#addition of numpy arrays
p8 = np.array([10,20])
p9 = np.array([30,40])


In [61]:
np.sum([p8,p9])

100

In [62]:
np.sum([p8,p9],axis=0)

array([40, 60])

In [63]:
np.sum([p8,p9],axis=1)

array([30, 70])

In [64]:
#mathematics with scalar value
t1 = np.array([10,20,30,40])

In [65]:
t1 = t1+1

In [66]:
t1

array([11, 21, 31, 41])

In [67]:
t1 = t1-1

In [68]:
t1

array([10, 20, 30, 40])

In [69]:
t1 = t1*2

In [70]:
t1

array([20, 40, 60, 80])

In [71]:
t1 = t1/2

In [72]:
t1

array([10., 20., 30., 40.])

In [73]:
np.mean(t1)

25.0

In [74]:
np.median(t1)

25.0

In [75]:
np.std(t1)

11.180339887498949

In [76]:
#numpy  save and load
n1 = np.array([10,20,30,40,50])

In [77]:
np.save('my_numpy',n1)

In [78]:
n1

array([10, 20, 30, 40, 50])

In [79]:
n2 = np.load('my_numpy.npy')

In [80]:
n2

array([10, 20, 30, 40, 50])